version: '3'

services:
  service-db:
    image: mongo:latest
    container_name: service_db
    ports:
      - 27017:27017
    volumes:
      - ./db/service_data:/data/db
    env_file:
      - ./db/.service.env
